-- schema.sql

-- 1. Rooms table
create table rooms (
   room_id         number
      generated by default on null as identity,
   room_number     varchar2(10) not null,
   room_type       varchar2(20) not null,
   price_per_night number(10,2) not null,
   status          varchar2(20) default 'Available',
   constraint pk_rooms primary key ( room_id )
);

-- 2. Guests table
create table guests (
   guest_id     number
      generated by default on null as identity,
   first_name   varchar2(50) not null,
   last_name    varchar2(50) not null,
   email        varchar2(100) unique not null,
   phone_number varchar2(20),
   constraint pk_guests primary key ( guest_id )
);

-- 3. Bookings table
create table bookings (
   booking_id     number
      generated by default on null as identity,
   guest_id       number not null,
   room_id        number not null,
   check_in_date  date not null,
   check_out_date date not null,
   total_amount   number(10,2) default 0,
   booking_status varchar2(20) default 'Confirmed',
   constraint pk_bookings primary key ( booking_id ),
   constraint fk_bookings_guest foreign key ( guest_id )
      references guests ( guest_id ),
   constraint fk_bookings_room foreign key ( room_id )
      references rooms ( room_id )
);

-- 4. Staff table (optional)
create table staff (
   staff_id   number
      generated by default on null as identity,
   first_name varchar2(50) not null,
   last_name  varchar2(50) not null,
   role       varchar2(20) not null,
   salary     number(10,2),
   constraint pk_staff primary key ( staff_id )
);

commit;